config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }
  root 'users#index'

  resources :users do
    member do
      resources :budgets do
        member do
          resources :enteries
        end
      end
    end
  end

end

app/models/budget.rb
class Budget < ActiveRecord::Base
  belongs_to :user
  has_many :enteries
  validates :title, :amount, presence: true
end

app/models/entery.rb
class Entery < ActiveRecord::Base
  belongs_to :budget
  self.inheritance_column = nil
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2, :twitter, :linkedin]
  has_many :budgets

  def self.find_for_oauth(access_token, signed_in_resource=nil)
    data = access_token.info

    if access_token.provider == "twitter"
      user = User.where(:email => "#{data["nickname"]}@twitter.com").first
    else
      user = User.where(:email => data["email"]).first
    end


    # users to be created if they don't exist
    if user.blank?
      user = User.new(email: data["email"],
                      password: Devise.friendly_token[0,20]
      )
      if access_token.provider == "twitter"
        user.email = "#{data["nickname"]}@twitter.com"
        user.save
      else
        user.save!
      end
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy, :debit, :debit_amount, :credit_amount]

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
    @enteries = @budget.enteries.paginate(:page => params[:page], per_page: 10)
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)
    @budget.balance =@budget.amount
    respond_to do |format|
      if @budget.save
        format.html { redirect_to budgets_path, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:title, :amount, :balance, :start_date, :end_date, :user_id)
    end
end

app/controllers/enteries_controller.rb
class EnteriesController < ApplicationController
  before_action :set_entery, only: [:show, :edit, :update, :destroy]

  # GET /enteries
  # GET /enteries.json
  def index
    @enteries = Entery.all
  end

  # GET /enteries/1
  # GET /enteries/1.json
  def show
  end

  # GET /enteries/new
  def new
    @entery = Entery.new
    @budget = Budget.find(params[:budget_id])
  end

  # GET /enteries/1/edit
  def edit
  end

  # POST /enteries
  # POST /enteries.json
  def create
    @entery = Entery.new(entery_params)
    @budget = @entery.budget
    respond_to do |format|
      if @budget.balance >= @entery.amount

          if @entery.save
            if @entery.type.eql? 1  #Debit
              @budget.balance += @entery.amount
            else if @entery.type.eql? 2  #Credit
                   @budget.balance -= @entery.amount   #Credit
                 end
            end
            @budget.save
            format.js { render :create, status: :created, location: @entery  }
          else
              format.html { render :new }
              format.json { render json: @entery.errors, status: :unprocessable_entity }
          end
      else
        format.js {
          @status = 'error'
          @message = 'Balance is insufficient for this transaction'
        }
      end


    end
  end
  # PATCH/PUT /enteries/1
  # PATCH/PUT /enteries/1.json
  def update
    respond_to do |format|
      if @entery.update(entery_params)
        format.html { redirect_to @entery, notice: 'Entery was successfully updated.' }
        format.json { render :show, status: :ok, location: @entery }
      else
        format.html { render :edit }
        format.json { render json: @entery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enteries/1
  # DELETE /enteries/1.json
  def destroy
    @entery.destroy
    respond_to do |format|
      format.html { redirect_to enteries_url, notice: 'Entery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entery
      @entery = Entery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entery_params
      params.require(:entery).permit(:title, :budget_id, :amount, :type)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    p '________________________'
    p request.env['omniauth.auth'].provider
    p '________________________'
    @user = User.find_for_oauth(request.env['omniauth.auth'], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => request.env['omniauth.auth'].provider.to_s #"Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      session['provider']= request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  alias_method :google_oauth2, :all
  alias_method :twitter, :all
  alias_method :facebook, :all
  alias_method :linkedin, :all
  alias_method :github, :all
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def show
   # redirect_to users_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/enteries_helper.rb
module EnteriesHelper
  def entry_type(type)
    if type==1
      p 'Debit'
    else
      p 'Credit'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/budgets/_form.html.slim
= simple_form_for @budget, wrapper: :horizontal_form do |f|
  = f.error_notification

  .col-md-5
    = f.input :title
    = f.input :amount, :disabled => true if @budget.persisted?
    = f.input :start_date, as: :string
    = f.input :end_date, as: :string
    = f.button :submit, class: 'btn btn-success'

app/views/budgets/debit.html.slim
.col-md-6.modal-content.centre
  h1 Debit Amount
  p= "Budget Title: #{@budget.title}"
  p= "Current balance: #{@budget.amount}"
  ruby:
    if @action == 'Debit'
      @url = debit_budget_path(@budget)
    else
      @url = credit_budget_path(@budget)
    end

  = simple_form_for @budget, url: @url, wrapper: :horizontal_form do |f|
    = f.error_notification
    = f.label :amount
    = text_field_tag :amount
    = f.button :submit, class: 'btn btn-success'

app/views/budgets/debit.js.erb
$("#modal-window").html("<%= j render template: 'budgets/debit.html.slim' %>");

$("#modal-window").on('hidden.bs.modal', function () {
    $("#modal-window").html('');
})

app/views/budgets/edit.html.slim
h1 Editing budget

== render 'form'

= link_to 'Show', @budget
'|
= link_to 'Back', budgets_path

app/views/budgets/index.html.slim
h3
  b Listing budgets
  hr

table.table
  thead
    tr.bg-success
      th Title
      th  Amount
      th Start Date
      th End Date
      th.text-center colspan='3' Actions

  tbody
    - @budgets.each do |budget|
      tr
        td = link_to budget.title, budget
        td = budget.amount
        td = budget.start_date
        td = budget.end_date
        td = link_to 'Show', budget
        td = link_to 'Edit', edit_budget_path(budget)
        td = link_to 'Destroy', budget, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Budget', new_budget_path, class: 'btn btn-success'

app/views/budgets/new.html.slim
h3
  b New budget
  = link_to 'Back', budgets_path, class: 'btn btn-primary pull-right'
  hr
== render 'form'

app/views/budgets/show.html.slim
#budget_div
  p#notice = notice

  table.table
    thead
      tr.bg-success
        th Title
        th  Amount
        th  Balance
        th Start Date
        th End Date
        th Actions

    tbody
      tr
        td = @budget.title
        td = @budget.amount
        td = @budget.balance
        td = @budget.start_date
        td = @budget.end_date
        td = link_to 'New entry', new_entery_path(budget_id: @budget.id),  { :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}

  #enteries_div
    = render 'enteries/index.html.slim'



  = link_to 'Edit', edit_budget_path(@budget)
  '|
  = link_to 'Back', budgets_path

app/views/enteries/_form.html.slim
.modal-content.centre
  h3 Create Entry
  = simple_form_for @entery,:remote => true, wrapper: :horizontal_form do |f|
    = f.error_notification

    .form-inputs
      = f.input :title
      = f.input :budget_id, :as => :hidden,:input_html => { :value => @budget.id }
      = f.input :amount
      = f.input :type , :collection => [['Debit', 1], ['Credit', 2]]

    .form-actions
      = f.button :submit, class: 'btn btn-success centre'

app/views/enteries/_index.html.slim
.col-md-12
  h2 Enteries
  table.table
    thead
      tr.bg-success
        th Title
        th Amount
        th Type
      tbody
        -@enteries.each do |e|
          tr
            td= e.title
            td= e.amount
            td= entry_type(e.type)
  = will_paginate @enteries

app/views/enteries/create.js.erb
<%- if @status.eql? 'error' %>
    alert("<%="#{@message}"%>");
<% else %>


$("#budget_div").html("<%= j render template: 'budgets/show.html.slim' %>");

$('#modal-window').modal('hide');
<% end %>

app/views/enteries/edit.html.slim
h1 Editing entery

== render 'form'

= link_to 'Show', @entery
'|
= link_to 'Back', enteries_path

app/views/enteries/new.js.erb
$("#modal-window").html("<%= j render template: 'enteries/new_entry' %>");

$("#modal-window").on('hidden.bs.modal', function () {
    $("#modal-window").html('');
})

app/views/enteries/new_entry.html.slim
.col-md-8.centre
  h1 New Entry

  = render 'form'

app/views/enteries/show.html.slim
p#notice = notice

p
  strong Title:
  = @entery.title
p
  strong Budget:
  = @entery.budget_id
p
  strong Amount:
  = @entery.amount
p
  strong Type:
  = @entery.type

= link_to 'Edit', edit_entery_path(@entery)
'|
= link_to 'Back', enteries_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Owallet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/base/jquery-ui.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class='navbar navbar-default navbar-inverse'>
  <div class='navbar-text col-md-12'>
    <% if user_signed_in? %>
        <div class="navbar-collapse collapse col-md-8" id="navbar">
          <ul class="nav navbar-nav">


          </ul>
        </div>
        <div class="col-md-4 pull-left">
          <p>
            <%= link_to 'My Budgets', budgets_path, :class => 'navbar-link'  %>
          </p>
        </div>
        <div class="col-md-4 pull-right">
          <p>

            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          </p>
        </div>


    <% else %>
        <%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to 'Login', new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </div>

</nav>
<%= yield %>


<div aria-hidden="true" aria-labelledby="myModalLabel" class="modal fade"  id="modal-window"  role="dialog">

</div>

</body>
</html>

app/views/users/index.html.slim
h1 Users#index
p Find me in app/views/users/_index.html.slim